import type { GetServerSidePropsResult, GetServerSidePropsContext } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import { Game } from "./api/src.types";
import { getPBs } from "./api/src";
import styles from "@/styles/Home.module.css";
import GameComponent from "@/components/game";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps({
  res,
}: GetServerSidePropsContext): Promise<
  GetServerSidePropsResult<{ games: Game[] }>
> {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );

  const games = await getPBs();
  return {
    props: { games },
  };
}

export default function Home({ games }: { games: Game[] }) {
  return (
    <>
      <Head>
        <title>SRC PBs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {games.map((game: Game) => (
          <GameComponent key={game.id} {...game} />
        ))}
      </main>
    </>
  );
}
